baseURL = 'https://suhasghorp.github.io/'
languageCode = 'en-us'
title = '&lt;quantexpr&gt;'
theme = 'hugo-kiera'
canonifyurls = true

[pagination]
  pagersize = 3
  path = 'page'

summaryLength = 10
enableEmoji = true
pygmentsCodeFences = true
