"""Generate the site's glossary from the engine's CONTEXT.md, the single source of truth for every term.

Writes:
  docs/fixed-income-risk/glossary.md          one section per group, one anchored heading per term
  includes/abbreviations.md hover tooltips for each term (and its plural), appended to every page

"In plain words" notes for newcomers live in data/plain-words.yml, keyed by term, and are merged in, so
re-running this script after a CONTEXT.md change never loses them. _Avoid_ lists are internal and dropped.

Usage: .venv/bin/python scripts/glossary.py [path/to/CONTEXT.md]
"""

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONTEXT = ROOT.parent / "fixed-income-risk" / "CONTEXT.md"

TERM = re.compile(r"^\*\*(?P<term>[^*]+)\*\*:\s*$")


def parse(context: str):
    """Returns [(group, [(term, definition)])] in document order."""
    groups, current = [], None
    lines = context.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("### "):
            current = (line[4:].strip(), [])
            groups.append(current)
        elif (match := TERM.match(line)) and current is not None:
            definition = []
            i += 1
            while i < len(lines) and lines[i].strip() and not lines[i].startswith("_Avoid_"):
                definition.append(lines[i].strip())
                i += 1
            current[1].append((match["term"].strip(), " ".join(definition)))
            continue
        i += 1
    return groups


def plural(term: str) -> str | None:
    if term.endswith(("s", "01")) or term[-1].isdigit():
        return None
    if term.endswith("y") and term[-2] not in "aeiou":
        return term[:-1] + "ies"
    if term.endswith(("ch", "sh", "x", "z")):
        return term + "es"
    return term + "s"


def plain_text(text: str) -> str:
    return re.sub(r"[_*`]", "", text).replace('"', "'")


def main() -> None:
    context_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CONTEXT
    groups = parse(context_path.read_text(encoding="utf-8"))
    notes_path = ROOT / "data" / "plain-words.yml"
    notes = yaml.safe_load(notes_path.read_text(encoding="utf-8")) or {} if notes_path.exists() else {}

    page = [
        "# Glossary",
        "",
        "Every term the series uses, defined exactly as the engine uses it. Hover a term in any article to see",
        "its definition.",
        "",
    ]
    abbreviations = ["<!-- Generated by scripts/glossary.py from the engine's CONTEXT.md. Do not edit by hand. -->"]
    known = set()
    for group, terms in groups:
        page += [f"## {group}", ""]
        for term, definition in terms:
            known.add(term)
            page += [f"### {term}", "", definition, ""]
            if term in notes:
                page += [f"*In plain words:* {notes[term].strip()}", ""]
            tooltip = plain_text(definition)
            abbreviations.append(f"*[{term}]: {tooltip}")
            if (plural_form := plural(term)) is not None:
                abbreviations.append(f"*[{plural_form}]: {tooltip}")
    unknown = sorted(set(notes) - known)
    if unknown:
        sys.exit(f"data/plain-words.yml has notes for terms not in CONTEXT.md: {unknown}")

    (ROOT / "docs" / "fixed-income-risk" / "glossary.md").write_text("\n".join(page).rstrip() + "\n", encoding="utf-8")
    (ROOT / "includes" / "abbreviations.md").write_text("\n".join(abbreviations) + "\n", encoding="utf-8")
    print(f"{len(known)} terms in {len(groups)} groups")


if __name__ == "__main__":
    main()
